export const skills = [
    { groupName: 'Programming Language', skill: 'C#', url: 'https://docs.microsoft.com/en-us/dotnet/csharp/' },
    { groupName: 'Programming Language', skill: 'Javascript', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript' },
    { groupName: 'Programming Language', skill: 'Typescript', url: 'https://www.typescriptlang.org/' },
    { groupName: 'Backend web frameworks', skill: 'asp.net core', url: 'https://docs.microsoft.com/en-us/aspnet/core/' },
    { groupName: 'Backend web frameworks', skill: 'asp.net mvc', url: 'https://docs.microsoft.com/en-us/aspnet/mvc/' },
    { groupName: 'Backend web frameworks', skill: 'express js', url: 'https://expressjs.com/' },
    { groupName: 'Cloud Technologies/Services', skill: 'Azure', url: 'https://azure.microsoft.com/en-us/' },
    { groupName: 'Software development', skill: 'Safe Agile', url: 'https://www.scaledagileframework.com/' },
    { groupName: 'Software development', skill: 'BDD', url: 'https://cucumber.io/docs/bdd/' },
    { groupName: 'Software development', skill: 'TDD', url: 'https://martinfowler.com/bliki/TestDrivenDevelopment.html' },
    { groupName: 'Mobile apps', skill: 'React Native apps', url: 'https://reactnative.dev/' },
    { groupName: 'Mobile apps', skill: 'Xamarin forms', url: 'https://dotnet.microsoft.com/apps/xamarin/xamarin-forms' },
    { groupName: 'Version control', skill: 'Git', url: 'https://git-scm.com/' },
    { groupName: 'Version control', skill: 'TFS', url: 'https://azure.microsoft.com/en-us/services/devops/server/' },
    { groupName: 'Software architecture patterns', skill: 'Monolith', url: 'https://martinfowler.com/bliki/MonolithFirst.html' },
    { groupName: 'Software architecture patterns', skill: 'Microservice', url: 'https://microservices.io/' },
    { groupName: 'Software architecture patterns', skill: 'micro front ends', url: 'https://micro-frontends.org/' },
    { groupName: 'Software architecture patterns', skill: 'JamStack', url: 'https://jamstack.org/' },
    { groupName: 'Software architecture patterns', skill: 'Event driven architecture', url: 'https://martinfowler.com/articles/201701-event-driven.html' },
    { groupName: 'Software architecture patterns', skill: 'serverless', url: 'https://serverless.com/' },
    { groupName: 'Azure service', skill: 'Azure AD', url: 'https://azure.microsoft.com/en-us/services/active-directory/' },
    { groupName: 'Azure service', skill: 'Azure Storage', url: 'https://azure.microsoft.com/en-us/services/storage/' },
    { groupName: 'Azure service', skill: 'Azure function', url: 'https://azure.microsoft.com/en-us/services/functions/' },
    { groupName: 'Azure service', skill: 'Event Grid', url: 'https://azure.microsoft.com/en-us/services/event-grid/' },
    { groupName: 'Azure service', skill: 'Event Hubs', url: 'https://azure.microsoft.com/en-us/services/event-hubs/' },
    { groupName: 'Azure service', skill: 'Cosmos Db', url: 'https://azure.microsoft.com/en-us/services/cosmos-db/' },
    { groupName: 'Azure service', skill: 'azure app services', url: 'https://azure.microsoft.com/en-us/services/app-service/' },
    { groupName: 'Azure service', skill: 'azure front door', url: 'https://azure.microsoft.com/en-us/services/frontdoor/' },
    { groupName: 'Azure service', skill: 'APIM', url: 'https://azure.microsoft.com/en-us/services/api-management/' },
    { groupName: 'Azure service', skill: 'Azure service bus(Queues/Topics)', url: 'https://azure.microsoft.com/en-us/services/service-bus/' },
    { groupName: 'Azure service', skill: 'Logic Apps', url: 'https://azure.microsoft.com/en-us/services/logic-apps/' },
    { groupName: 'Azure service', skill: 'Durable functions', url: 'https://docs.microsoft.com/en-us/azure/azure-functions/durable/' },
    { groupName: 'Azure service', skill: 'Key vault', url: 'https://azure.microsoft.com/en-us/services/key-vault/' },
    { groupName: 'Azure service', skill: 'Azure app insights', url: 'https://azure.microsoft.com/en-us/services/monitor/' },
    { groupName: 'Frontend libraries/frameworks', skill: 'React', url: 'https://reactjs.org/' },
    { groupName: 'Frontend libraries/frameworks', skill: 'Angular', url: 'https://angular.io/' },
    { groupName: 'Frontend libraries/frameworks', skill: '11ty', url: 'https://www.11ty.dev/' },
    { groupName: 'Frontend libraries/frameworks', skill: 'Jquery', url: 'https://jquery.com/' },
    { groupName: 'Frontend libraries/frameworks', skill: 'Rxjs', url: 'https://rxjs.dev/' },
    { groupName: 'Frontend libraries/frameworks', skill: 'MUI react', url: 'https://mui.com/' },
    { groupName: 'Frontend libraries/frameworks', skill: 'Angular material', url: 'https://material.angular.io/' },
    { groupName: 'Frontend libraries/frameworks', skill: 'Prime NG', url: 'https://www.primefaces.org/primeng/' },
    { groupName: 'TEMPLATE LANGUAGES', skill: 'HTML', url: 'https://developer.mozilla.org/en-US/docs/Web/HTML' },
    { groupName: 'TEMPLATE LANGUAGES', skill: 'NUNJUCKS', url: 'https://mozilla.github.io/nunjucks/' },
    { groupName: 'TEMPLATE LANGUAGES', skill: 'Razor', url: 'https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor' },
    { groupName: 'CSS frameworks', skill: 'Tailwind', url: 'https://tailwindcss.com/' },
    { groupName: 'CSS frameworks', skill: 'Bootstrap', url: 'https://getbootstrap.com/' },
    { groupName: 'CSS frameworks', skill: 'CSS', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS' },
    { groupName: 'CSS frameworks', skill: 'Styled components', url: 'https://styled-components.com/' },
    { groupName: 'Database', skill: 'Sql server', url: 'https://www.microsoft.com/en-us/sql-server/sql-server-2019' },
    { groupName: 'Database', skill: 'Mongodb', url: 'https://www.mongodb.com/' },
    { groupName: 'Database', skill: 'Cosmos db', url: 'https://azure.microsoft.com/en-us/services/cosmos-db/' },
    { groupName: 'ORM', skill: 'EF Core', url: 'https://docs.microsoft.com/en-us/ef/core/' },
    { groupName: 'ORM', skill: 'ado.net', url: 'https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/' },
    { groupName: 'ORM', skill: 'prisma', url: 'https://www.prisma.io/' },
    { groupName: 'Testing Frameworks', skill: 'Playwright', url: 'https://playwright.dev/' },
    { groupName: 'Testing Frameworks', skill: 'Selenium', url: 'https://www.selenium.dev/' },
    { groupName: 'Testing Frameworks', skill: 'NUnit', url: 'https://nunit.org/' },
    { groupName: 'Devops', skill: 'Teamcity', url: 'https://www.jetbrains.com/teamcity/' },
    { groupName: 'Devops', skill: 'octopus', url: 'https://octopus.com/' },
    { groupName: 'Devops', skill: 'gitlab', url: 'https://about.gitlab.com/' },
    { groupName: 'Devops', skill: 'azure devops', url: 'https://azure.microsoft.com/en-us/services/devops/' },
    { groupName: 'Devops', skill: 'Docker', url: 'https://www.docker.com/' },
    { groupName: 'API design and development', skill: 'OPEN API', url: 'https://swagger.io/specification/' },
    { groupName: 'API design and development', skill: 'Swagger', url: 'https://swagger.io/' },
    { groupName: 'API design and development', skill: 'Stoplight', url: 'https://stoplight.io/' },
    { groupName: 'API design and development', skill: 'Graphql', url: 'https://graphql.org/' },
    { groupName: 'Authentication', skill: 'Oauth', url: 'https://oauth.net/' },
    { groupName: 'Authentication', skill: 'Open id connect', url: 'https://openid.net/connect/' },
    { groupName: 'Authentication', skill: 'Forms authentication', url: 'https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-5.0' },
    { groupName: 'Authentication', skill: 'Identity server', url: 'https://identityserver.io/' },
];